---
title: Zitate
created_at: 2021-04-05
updated_at: 2022-01-24
---

"Man darf nicht glauben, eine Idee könne durch den Beweis ihrer Richtigkeit selbst bei gebildeten Geistern Wirkungen erzielen."
-- aus dem Buch »Psychologie der Massen« von Gustave Le Bon, S.65

"Garbage in, garbage out."
-- aus dem Buch »Steal like an artist« von Austin Kleon, S.13

"If you want to make a difference, pick a standard and get started.
If you want to be a highly paid consultant, take simple things and obfuscate them with jargon and nonsense."
-- https://www.quora.com/What-are-the-differences-between-data-integrity-and-data-quality/answer/John-Kimmett?ch=10&share=a9b29cef[John Kimmett]

"Don’t make regular expressions do what they’re not good at.
If you want to match a simple pattern, then match a simple pattern.
If you want to do math, then do math."
-- https://devblogs.microsoft.com/oldnewthing/?p=31113[Raymond / devblogs.microsoft.com]

"I contend that we are both atheists.
I just believe in one fewer god than you do.
When you understand why you dismiss all the other possible gods, you will understand why I dismiss yours."
-- Stephen Roberts

"Das Gegenteil von gut ist gut gemeint."
-- https://german.stackexchange.com/a/1769, https://falschzitate.blogspot.com/2017/04/das-gegenteil-von-gut-ist-gut-gemeint.html

"A fool with a tool is still a fool."
-- Grady Booch

"Es gibt momentan nichts, wovon ich meine, es sagen zu müssen.
Wenn ich etwas zu sagen habe, werde ich es tun, bitte lassen Sie mich so lange in Ruhe."
-- Schüler in Singapur, aus dem Buch »Still und Stark« von Susan Cain, S.274

"What you want to do and what you can do are different things.
I think "doing what you can" makes you a pro, and then you grow to love it."
-- Twitter Post in »My Solo Exchange Diary« von Nagata Kabi, S.88

"The trick is not to spend time developing a combination hammer/screwdriver, but just use a hammer and a screwdriver."
-- commenter Maurits

"Am Baume des Schweigens hängt seine Frucht, der Friede."
-- arabisches Sprichwort

"Arguments over style are pointless. There should be a style guide, and you should follow it."
-- Rebecca Murphey

"Part of being a good steward to a successful project is realizing that writing code for yourself is a Bad Idea™.
If thousands of people are using your code, then write your code for maximum clarity, not your personal preference of how to get clever within the spec."
-- Idan Gazit

"Under no circumstances should you program the way I say to because I say to; program the way you think expresses best what you’re trying to accomplish in the program.
And do so consistently and ruthlessly."
-- Rob Pike

"Think before you speak. Read before you think."
-- Fran Lebowitz, The Fran Lebowitz Reader

"Debugging is twice as hard as writing the code in the first place.
Therefore, if you write the code as cleverly as possible, you are, by definition, not smart enough to debug it."
-- Brian W. Kernighan and P. J. Plauger in The Elements of Programming Style.

"If you want your customers to love your company, the employees need to love it first."
-- Simon Sinek

== aus Büchern

* link:/zitate/psychologie_der_massen[Psychologie der Massen, Gustave Le Bon]

== Zitatsammlungen

* https://morr.cc/zitate/
* https://morr.cc/quotes/
* http://michael-puff.de/Programmierung/Artikel/Programmier-Zitate.shtml