---
title: Amazon.de
created_at: 2021-11-12
tags:
- Amazon
- Versandhandel
---

== Preise

Die Preise schwanken teilweise _extrem_ stark.
Ein Logitech G923 PS4 Lenkrad schwankte innerhalb von Tagen zwischen €250 - €400 (UVP).
Ein Thrustmaster T300 RS GT schwankte innerhalb von Tagen zwischen €300 - €400 (UVP).

== Amazon Warehouse

Ich habe bisher drei Geräte bei Amazon Warehouse gekauft.
Der TV ist geblieben.
Die beiden Lenkräder gingen zurück.

Das erste war ein TV.
»Zustand: Gebraucht - Sehr gut - Der Artikel wird in der Originalverpackung zugestellt Die Verpackung wird beschädigt sein.«
Versand war in OVP.
Die Verpackung hatte einen ordentlichen Macken.
Das Gerät an sich war aber einwandfrei.

Das zweite war ein PS4 Lenkrad.
»Zustand: Gebraucht - Gut - Kleine Schönheitsfehler an der Ober- oder Vorderseite oder an den Seiten des Artikels. Zubehör weist ggf. optische Mängel auf. Der Artikel wird in der Originalverpackung zugestellt Die Verpackung wird beschädigt sein.«
Ich habe explizit eine Amazon Umverpackung ausgewählt.
Die OVP war deutlich beschädigt.
Das Lenkrad allerdings war ohne sichtbare Mängel.
Der Preis erschien gut.
Statt UVP 400 waren es €256,93.
Allerdings gab es das Lenkrad paar Tage danach neu für €250.

Das dritte war ein PS3/PS4 Lenkrad.
»Zustand: Gebraucht - Sehr gut - Kleine Schönheitsfehler an der Ober- oder Vorderseite oder an den Seiten des Artikels. Artikel trifft neu verpackt ein.«
Der Versand sollte in OVP erfolgen.
Ich habe explizit eine Amazon Umverpackung ausgewählt.
Nach dem öffnen der Amazon Verpackung bin ich fast umgekippt.
Das Lenkrad, Pedale etc waren lose in der Amazon Verpackung!
OVP nicht vorhanden.
Schlecht ausgepolstert.
Es war ein Wunder, dass alle Teile ohne sichtbare Mängel ankamen.
