---
title: Auf dem Boden sitzen und schlafen
created_at: 2021-05-31
updated_at: 2021-12-18
---

Wir schlafen seit etwa Februar 2015 auf einer Tatami Matte und Futon aus acht Lagen Baumwolle.
Für mich als 60kg leichten Rückenschläfer ideal.
Seitenschläfer sollten einen dickeren Futon verwenden.
Oder einen mit Schafwolle, da diese sich nicht so platt drücken wie Baumwolle.

Seit 2019 schalfe ich ohne Kissen.
Am Anfang war es durchaus anstrengend.
Allerdings vermisse ich es inzwischen nicht mehr.

Seit 2020 sitze ich in meinem Zimmer auf dem Boden.
Mein Schreibtisch ist selbstgebaut.
Darunter ist eine Tatami Matte und ein Futon aus drei Lagen Baumwolle.
Ein Zaisu habe ich ebenfalls.
Vor dem Fernseher verwende ich ein Tatami Kissen.
Also eine miniatur Tatami Matte.

Seit etwa 2020/2021 sitzen wir auch im Wohnzimmer auf dem Boden.

== japanische Begriffe

[horizontal]
畳:: Tatami, Bodenbelag aus gepresstem Reisstroh
布団:: Futon, Matte aus 100% Baumwolle
shiki:: Futon-Matte (shikibuton, 敷布団, shikifuton), 3-4" (7,5-10,1 cm) / 6-10cm / ca 5cm Dicke, Matratze
kake:: Futon-Matte (kakebuton, 掛布団), dünner als shiki, Decke
futontataki:: Futon Klopfer, 布団叩き, Teppichklopfer
sobakawa:: Kissen aus Buchweizenschalen/Buchweizenspreu
ryokan (旅館):: traditionelles japanisches Hotel
washitsu (和室):: japanischer Raum
zafu:: Sitzkissen
zaisu:: Sitzstuhl
zabuton:: Sitzkissen
zataku:: ざたく 【 座卓 】 / Chabudai, niedriger Tisch, 33-40 cm hoch
kotatsu:: niedriger Tisch mit Wärmelampe, Kotatsu Futon und Brett

== Online Shops

* https://www.edofuton.de
** Japan Futon 6.0, 6 Lagen Baumwolle, 10-12cm dicke
** Futon 4.0 Shiatsu, 4 Lagen Baumwolle, 6-8cm dicke
** Rollfuton Gästefuton 3.0 Baumwolle, 3 Lagen Baumwolle, 6-8cm dicke
* https://www.futonwerk.de

== Referenzen

=== sitzen

* https://youtu.be/lk6iBopDPgA

=== schlafen

* https://voyapon.com/de/futon-in-japan-schlafen-auf-dem-boden/
* https://www.nytimes.com/wirecutter/blog/japanese-futon/
* https://dengarden.com/interior-design/Shikibuton-Japanese-Traditional-Futon
* https://jlifeinternational.com/blogs/news/a-complete-guide-to-the-japanese-sleep-system
* https://japanjunky.com/why-do-the-japanese-sleep-on-floors/
* https://www.futonwerk.de/futon.html
* https://futontokyo.com/what-is-a-futon/handy-tools/
* https://gogonihon.com/de/blog/japanisches-bett-traditionell-schlafen-auf-einem-futon/