---
title: Introversion, Extraversion, Ambiversion
created_at: 2021-05-05
updated_at: 2021-10-01
---

Introvertierte sind das eine Extrem, Extravertierte das andere und die Ambivertierten sind quasi mittig dazwischen.

Es sind angeborene Charaktereigenschaften.
Nicht gut, nicht schlecht, nicht besser, nicht schlechter.
Einfach nur Charaktereigenschaften die respektiert werden müssen.

Ein Introvertierter fühlt sich wohl, wenn er alleine ist.
Ein Extravertierter fühlt sich wohl, wenn er umgeben von anderen ist.
Dabei ist alleine sein nicht das selbe wie einsam sein.
Gesellschaft kann natürlich auch von Introvertierten genossen werden.
Ebenso können Extravertierte Ruhe und Stille geniesen.
Es ist nur so, dass Introvertierte vom Geselligsein eine Pause brauchen und Extravertierte vom Alleinsein.

Ich persöhnlich hatte schon als Jugendlicher gemerkt, dass ich meistens nach drei Stunden "mit jemandem Zeit verbringen" genug hatte.
Danach war ich erschöpft und musste mich alleine in meinem Zimmer ausruhen.
Andere waren maximal zum Schlafen alleine.
Als erwachsener ist es nicht viel anders bei mir.
Ein paar Stunden im Einkaufszentrum und das wars dann für den Tag.

Extravertierte können nicht verstehen wie jemand so lange wie ich alleine sein kann.
Ich wiederum kann nicht verstehen wie jemand permanent von Leuten umgeben sein kann.
Allerdings respektiere ich das.
Ich versuche niemandem auszureden möglichst viele Leute um sich zu scharen.
Wäre schön, wenn allgemein akzeptiert werden würde, dass Introvertierte gerne ihre Ruhe haben.

== Bücher

* Still: Die Kraft der Introvertierten, Susan Cain, ISBN 3442157648
* Still und Stark: Die Kraft introvertierter Kinder und Jugendlicher, Susan Cain, ISBN 3442159284
* Introvert: The friendly takeover, Linus Jonkman, ISBN 9198327618
** die deutsche Version ist eingedeutscht, es liest sich seltsam, bin mitten drin auf die englische Version umgestiegen

== Links

* https://www.introvertiert.org/92-eigenschaften-von-introvertierten[92 Eigenschaften von Introvertierten]
* https://introvertdear.com/what-is-an-introvert-definition/[What Is an Introvert? Definition & Guide to Introversion]