---
title: self hosting
created_at: 2022-08-18
updated_at: 2023-04-25
---

* https://github.com/grempe/diceware[diceware (grempe)]
* https://github.com/dani-garcia/vaultwarden[vaultwarden]

== Archivierung

* https://github.com/ArchiveBox/ArchiveBox[ArchiveBox]

== Bookmarks

=== linkding

NOTE: Stand 2022-09-28

https://github.com/sissbruecker/linkding[github sissbruecker/linkding]

Das Dockerfile wirkt nicht rund.
Es wird kein Benutzer angelegt.
Man muss etwas rumtricksen, damit nicht der ganze Container als root läuft.
Die Datei `/etc/linkding/secretkey.txt` wird in einem Verzeichnis angelegt, das root gehört.
Es wird ein `bootstrap.sh` Skript ausgeführt, aber am Ende erfolgt kein `exec`.

Es ist nicht dokumentiert, wie man an die Client IP hinter einem Proxy dran kommt.
Entweder `uwsgi.ini` mit `log-x-forwarded-for = true` einbinden.
Oder die Umgebungsvariable `UWSGI_LOG_X_FORWARDED_FOR=true` setzen.

Fehlerhafte Anmeldeversuche werden nicht geloggt.
Ein `200` er Status hilft wenig.
Es ist zwar im Webinterface entsprechend dargestellt, aber Crowdsec etc können nicht darauf reagieren.

Man sollte sich mit uwsgi und evt Django auskennen.

=== link-warden

NOTE: Stand 2022-09-30

https://github.com/Daniel31x13/link-warden[github Daniel31x13/link-warden]

Scheint keine Authentifizierung zu unterstützen.

=== briefkasten

NOTE: Stand 2022-09-30

https://github.com/ndom91/briefkasten[github ndom91/briefkasten]

Authentifizierung nur über Google, Github und Email Versand.

=== shiori

NOTE: Stand 2022-09-30

Hinter einem Proxy wird nicht die Client IP geloggt.

=== NeonLink

NOTE: Stand 2022-09-30

Das Dockerfile lässt zu wünschen übrig.
Es werden u.a. Warnungen ausgegeben, dass `--omit=dev` verwendet werden soll anstatt `--only=production`.
Es wird kein Benutzer angelegt und der Container läuft als root.

Lies sich nicht starten.

== git

* https://wiki.archlinux.org/title/Cgit[Cgit]
* https://wiki.archlinux.org/title/Gitolite[Gitolite]

== pastebin

* https://github.com/WantGuns/bin[bin - highly opinionated, minimal pastebin]
* https://github.com/matze/wastebin[wastebin is a pastebin]

== Referenzen

* https://github.com/awesome-selfhosted/awesome-selfhosted[Awesome-Selfhosted (github repo)]
* https://jvns.ca/blog/2022/01/24/hosting-my-static-sites-with-nginx/[Hosting my static sites with nginx (Julia Evans)]
* https://blog.wesleyac.com/posts/how-i-run-my-servers[How I run my servers (Wesley Aptekar-Cassels)]
